version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: dofus_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cho3Ohmo
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
