name: CI

on: [pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install Diesel CLI
        run: cargo install diesel_cli --no-default-features --features postgres

      - name: Set up database URL
        run: echo "TEST_DATABASE_URL=postgres://postgres:test@localhost:5432/postgres" >> $GITHUB_ENV

      - name: Run Diesel migrations
        env:
          DATABASE_URL: ${{ env.TEST_DATABASE_URL }}
        run: diesel migration run

      - name: Run tests
        env:
          TEST_DATABASE_URL: ${{ env.TEST_DATABASE_URL }}
        run: cargo test -- --nocapture
